baseURL = "https://blog.seppedekeyser.be"
languageCode = "en-us"
title = "Rendering Pixels"
theme = "terminal"

[permalinks]
  posts = "/:year/:month/:title"

[params]
  themeColor = "blue"
  fullWidthTheme = false
  centerTheme = true

[params.Twitter]
  creator = "SeppahBaws"
  site = "SeppahBaws"

[languages]
  [languages.en.params.logo]
    logoText = "Seppe's Blog"
