baseURL = "https://renderingpixels.com"
languageCode = "en-us"
title = "Rendering Pixels"
theme = "terminal"
copyright = "© 2022 - Seppe Dekeyser"

[permalinks]
  posts = "/:year/:month/:title"

[params]
  themeColor = "blue"
  fullWidthTheme = false
  centerTheme = true
  showMenuItems = 2
  showLastUpdated = true
  oneHeadingSize = false

[params.Twitter]
  creator = "SeppahBaws"
  site = "SeppahBaws"

[markup.tableOfContents]
  endLevel = 6
  startLevel = 1

[params.logo]
  logoText = "Rendering Pixels"

[menu]
  [[menu.main]]
    identifier = "01-posts"
    name = "See All Posts"
    url = "/posts"
  [[menu.main]]
    identifier = "02-portfolio"
    name = "My Portfolio"
    url = "https://seppedekeyser.be"
